DROP TABLE IF EXISTS Administrators;
DROP TABLE IF EXISTS PendingTransactions;
DROP TABLE IF EXISTS PendingOrganisations;
DROP TABLE IF EXISTS SessionTokens;
DROP TABLE IF EXISTS AccountTokens;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS AgeRanges;
DROP TABLE IF EXISTS Organisations;





