#! /bin/bash

eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

YESTERDAY=`date -d "yesterday" +%F`


./script/pear-local_loop leaderboard -t daily_total -d $YESTERDAY
./script/pear-local_loop leaderboard -t daily_count -d $YESTERDAY
./script/pear-local_loop leaderboard -t all_time_total -d $YESTERDAY
./script/pear-local_loop leaderboard -t all_time_count -d $YESTERDAY
