#! /usr/bin/env perl

use strict;
use warnings;

use FindBin qw/ $Bin /;
use lib "$Bin/../lib";

use Pear::LocalLoop::Schema;

my @con = @ARGV;

my $schema = Pear::LocalLoop::Schema->connect(@con);

$schema->deploy;
